{"name": "test_get_auth_code[info0]", "status": "broken", "statusDetails": {"message": "UnboundLocalError: cannot access local variable 'new_resp' where it is not associated with a value", "trace": "self = <test_api_funcs.TestApiFuncs object at 0x0000023C4889AD50>\ninfo = {'extract': None, 'module': 'xxx', 'request': {'headers': None, 'json': None, 'method': None, 'url': None}, 'title': '获取Auth鉴权码', ...}\n\n    @pytest.mark.parametrize('info', get_cases_data(data))\n    def funcs(self, info):\n        logger.info('===========================开始执行===========================')\n>       excute_cases(info)\n\ntestcases\\test_api_funcs.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommons\\cases.py:22: in excute_cases\n    info = replace_data(verfiy_module(info))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = {'extract': None, 'module': 'xxx', 'request': {'headers': None, 'json': None, 'method': None, 'url': None}, 'title': '获取Auth鉴权码', ...}\n\n    def replace_data(resp):\n        replace_expr = '\\\\$\\\\{(.*?)\\\\((.*?)\\\\)\\\\}'\n        str_resp = json.dumps(resp)\n    \n        if '${' in str_resp and '}' in str_resp:\n            result_list = re.findall(replace_expr, str_resp)\n            logger.info(f'result_list: {result_list}')\n            for func_info in result_list:\n                func_name, func_args = func_info\n                old_value = '${'+func_name+'('+func_args+')}'\n                if func_args == '':\n                    new_value = getattr(HotLoads(), func_name)()\n                elif ',' in func_args:\n                    new_value = getattr(HotLoads(), func_name)(*func_args.split(','))\n                else:\n                    new_value = getattr(HotLoads(), func_name)(func_args)\n                new_str_resp = str_resp.replace(old_value, new_value)\n            new_resp = json.loads(new_str_resp, strict=False)\n    \n>       return new_resp\n               ^^^^^^^^\nE       UnboundLocalError: cannot access local variable 'new_resp' where it is not associated with a value\n\ncommons\\replace_template.py:29: UnboundLocalError"}, "attachments": [{"name": "log", "source": "ebf12d04-9fc6-4362-a84d-add09e916d60-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "info", "value": "{'module': 'xxx', 'title': '获取Auth鉴权码', 'request': {'url': None, 'method': None, 'headers': None, 'json': None}, 'extract': None, 'validate': None}"}], "start": 1750156070103, "stop": 1750156070104, "uuid": "bc2e9800-8f18-4051-a4e0-edfa22615470", "historyId": "c400c38184742bd26a9c4d0dd01b4b5e", "testCaseId": "07afc847c9e20a5dbdcd3f170543c6e7", "fullName": "testcases.test_api_funcs.TestApiFuncs#test_get_auth_code", "labels": [{"name": "epic", "value": "接口自动化测试报告"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_api_funcs"}, {"name": "subSuite", "value": "TestApiFuncs"}, {"name": "host", "value": "cxj175"}, {"name": "thread", "value": "6796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_api_funcs"}]}